/*
 * (1.3) Parser: PARSING
 * ------------------------------------------------------
 * ------------------------------------------------------
 * This will operate on the tokens generated by the lexer, establishing programs.
 *
 */

function Parser() {
  const ARG_START = "(";
  const ARG_STOP = ")";
  const ARG_SEPARATOR = ",";

  function parseLambda() {
    return {
      type: "lambda",
      vars: argumentDelimitor(ARG_START, ARG_STOP, ARG_SEPARATOR, parseVarname),
      body: parseExpression(),
    };
  }

  function skipPunctuation() {
    return null;
  }

  function isPunctuation() {
    return null;
  }

  function argumentDelimitor(start, stop, separator, parser) {
    var args = [];
    var first = true;
    return "No parsing expression";
  }

  function parseExpression() {
    return "No parsing expression";
  }
}
